# 
stages:
  - build
  - test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

image: "rust:latest"

before_script:
  - rustc --version
  - cargo --version
  - rustup component add rustfmt
  - rustup component add clippy
  - apt-get update && apt-get install -y libgtk-3-dev

build_job:
  stage: build
  script:
  - cargo fmt --all -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build --verbose --all
  artifacts:
    paths:
      - target/

test_job:
  stage: test
  script:
    - cargo test --verbose --all


